/*
 * File: Specification.cpp
 *
 * Copyright (C) 2021, Albert Krzymowski
 *
 */

#include "Specification.h"

namespace ELF {
namespace Map {
/*************************************************************************/

::Tools::ValueMap Class("Class", {
 { ELFCLASSNONE,	"ELFCLASSNONE" },
 { ELFCLASS32,		"ELFCLASS32" },
 { ELFCLASS64,		"ELFCLASS64" },
});

::Tools::ValueMap Data("Data", {
    { ELFDATANONE, "ELFDATANONE" },  
    { ELFDATA2LSB, "ELFDATA2LSB" },  
    { ELFDATA2MSB, "ELFDATA2MSB" },  
});

::Tools::ValueMap Version("Version", {
    { EV_NONE,     "EV_NONE" },
    { EV_CURRENT, "EV_CURRENT" },
});

::Tools::ValueMap DynamicTag("DynamicTag", {
 { DT_NULL, "NULL" },
 { DT_NEEDED, "NEEDED" },
 { DT_PLTRELSZ, "PLTRELSZ" },
 { DT_PLTGOT, "PLTGOT" },
 { DT_HASH, "HASH" },
 { DT_STRTAB, "STRTAB" },
 { DT_SYMTAB, "SYMTAB" },
 { DT_RELA, "RELA" },
 { DT_RELASZ, "RELASZ" },
 { DT_RELAENT, "RELAENT" },
 { DT_STRSZ, "STRSZ" },
 { DT_SYMENT, "SYMENT" },
 { DT_INIT, "INIT" },
 { DT_FINI, "FINI" },
 { DT_SONAME, "SONAME" },
 { DT_RPATH, "RPATH" },
 { DT_SYMBOLIC, "SYMBOLIC" },
 { DT_REL, "REL" },
 { DT_RELSZ, "RELSZ" },
 { DT_RELENT, "RELENT" },
 { DT_PLTREL, "PLTREL" },
 { DT_DEBUG, "DEBUG" },
 { DT_TEXTREL, "TEXTREL" },
 { DT_JMPREL, "JMPREL" },
 { DT_BIND_NOW, "BIND_NOW" },
 { DT_INIT_ARRAY, "INIT_ARRAY" },
 { DT_FINI_ARRAY, "FINI_ARRAY" },
 { DT_INIT_ARRAYSZ, "INIT_ARRAYSZ" },
 { DT_FINI_ARRAYSZ, "FINI_ARRAYSZ" },
 { DT_RUNPATH, "RUNPATH" },
 { DT_FLAGS, "FLAGS" },
 { DT_ENCODING, "ENCODING" },
 { DT_PREINIT_ARRAY, "PREINIT_ARRAY" },
 { DT_PREINIT_ARRAYSZ, "PREINIT_ARRAYSZ" },
 { DT_MAXPOSTAGS, "MAXPOSTAGS" },
 { DT_LOOS, "LOOS" },
 { DT_SUNW_AUXILIARY, "SUNW_AUXILIARY" },
 { DT_SUNW_RTLDINF, "SUNW_RTLDINF" },
 { DT_SUNW_FILTER, "SUNW_FILTER" },
 { DT_SUNW_CAP, "SUNW_CAP" },
 { DT_SUNW_SYMTAB, "SUNW_SYMTAB" },
 { DT_SUNW_SYMSZ, "SUNW_SYMSZ" },
 { DT_SUNW_ENCODING, "SUNW_ENCODING" },
 { DT_SUNW_SORTENT, "SUNW_SORTENT" },
 { DT_SUNW_SYMSORT, "SUNW_SYMSORT" },
 { DT_SUNW_SYMSORTSZ, "SUNW_SYMSORTSZ" },
 { DT_SUNW_TLSSORT, "SUNW_TLSSORT" },
 { DT_SUNW_TLSSORTSZ, "SUNW_TLSSORTSZ" },
 { DT_SUNW_CAPINFO, "SUNW_CAPINFO" },
 { DT_SUNW_STRPAD, "SUNW_STRPAD" },
 { DT_SUNW_CAPCHAIN, "SUNW_CAPCHAIN" },
 { DT_SUNW_LDMACH, "SUNW_LDMACH" },
 { DT_SUNW_CAPCHAINENT, "SUNW_CAPCHAINENT" },
 { DT_SUNW_CAPCHAINSZ, "SUNW_CAPCHAINSZ" },
 { DT_HIOS, "HIOS" },
 { DT_VALRNGLO, "VALRNGLO" },
 { DT_CHECKSUM, "CHECKSUM" },
 { DT_PLTPADSZ, "PLTPADSZ" },
 { DT_MOVEENT, "MOVEENT" },
 { DT_MOVESZ, "MOVESZ" },
 { DT_POSFLAG_1, "POSFLAG_1" },
 { DT_SYMINSZ, "SYMINSZ" },
 { DT_SYMINENT, "SYMINENT" },
 { DT_VALRNGHI, "VALRNGHI" },
 { DT_ADDRRNGLO, "ADDRRNGLO" },
 { DT_GNUHASH, "GNUHASH" },
 { DT_CONFIG, "CONFIG" },
 { DT_DEPAUDIT, "DEPAUDIT" },
 { DT_AUDIT, "AUDIT" },
 { DT_PLTPAD, "PLTPAD" },
 { DT_MOVETAB, "MOVETAB" },
 { DT_SYMINFO, "SYMINFO" },
 { DT_ADDRRNGHI, "ADDRRNGHI" },
 { DT_RELACOUNT, "RELACOUNT" },
 { DT_RELCOUNT, "RELCOUNT" },
 { DT_FLAGS_1, "FLAGS_1" },
 { DT_VERDEF, "VERDEF" },
 { DT_VERDEFNUM, "VERDEFNUM" },
 { DT_VERNEED, "VERNEED" },
 { DT_VERNEEDNUM, "VERNEEDNUM" },
 { DT_LOPROC, "LOPROC" },
 { DT_SPARC_REGISTER, "SPARC_REGISTER" },
 { DT_AUXILIARY, "AUXILIARY" },
 { DT_USED, "USED" },
 { DT_FILTER, "FILTER" },
 { DT_HIPROC, "HIPROC" }
});

/*************************************************************************/
}
}